<a href="https://colab.research.google.com/github/MdShajalalsojib/Data-Mining-Lab/blob/main/data_pre_prcoessing_002.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas --q

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/Ataullha/CSE-412_Machine-Learning-Lab/refs/heads/main/titanic_train.csv")

In [ ]:
df.head(2)
df.tail()
df.sample(5)

,passenger_id,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,survived
133,1180,3,"Sage, Mrs. John (Annie Bullen)",female,NaN,1,9,CA. 2343,69.55,NaN,S,NaN,NaN,NaN,0
226,1187,3,"Sandstrom, Miss. Beatrice Irene",female,1.0,1,1,PP 9549,16.70,G6,S,13,NaN,NaN,1
211,424,2,"Givard, Mr. Hans Kristensen",male,30.0,0,0,250646,13.00,NaN,S,NaN,305.0,NaN,0
388,1073,3,"O'Connor, Mr. Maurice",male,NaN,0,0,371060,7.75,NaN,Q,NaN,NaN,NaN,0
160,83,1,"Crosby, Mrs. Edward Gifford (Catherine Elizabe...",female,64.0,1,1,112901,26.55,B26,S,7,NaN,"Milwaukee, WI",1

In [ ]:
len(df.columns)
len(df)

850

In [ ]:
df.shape

(850, 15)

In [ ]:
type(df['age'])

pandas.core.series.Series

In [ ]:
type(df[['age']])

pandas.core.frame.DataFrame

In [ ]:
df['age']

0       NaN
1      38.0
2      30.0
3      54.0
4      40.0
       ...
845    55.0
846    58.0
847    24.0
848     3.0
849    52.0
Name: age, Length: 850, dtype: float64

In [ ]:
df['age'].isnull().sum()

np.int64(174)

In [ ]:
df['age'] = df['age'].fillna(df['age'].mean())

df['age'] = df['age'].fillna(df['age'].median())
df['age'] = df['age'].fillna(df['age'].mode())
df['age'] = df['age'].fillna(df['age'].min())
df['age'] = df['age'].fillna(df['age'].max())

In [ ]:
df['age'].isnull().sum()

np.int64(0)

In [ ]:
df.columns

Index(['passenger_id', 'pclass', 'name', 'sex', 'age', 'sibsp', 'parch',
       'ticket', 'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest',
       'survived'],
      dtype='object')

In [ ]:
# df = df.drop("name",axis=1)

df.drop("name",axis=1,inplace=True)

In [ ]:
len(df.columns)

14

In [ ]:
df.describe()

,passenger_id,pclass,age,sibsp,parch,fare,body,survived
count,850.000000,850.00000,850.000000,850.000000,850.000000,849.000000,73.000000,850.000000
mean,662.816471,2.32000,29.519847,0.522353,0.382353,34.012701,165.821918,0.368235
std,380.751936,0.83853,12.984533,1.112132,0.879511,53.705779,99.068487,0.482610
min,1.000000,1.00000,0.166700,0.000000,0.000000,0.000000,4.000000,0.000000
25%,332.250000,2.00000,22.000000,0.000000,0.000000,7.895800,75.000000,0.000000
50%,676.500000,3.00000,29.519847,0.000000,0.000000,14.108300,166.000000,0.000000
75%,992.250000,3.00000,34.875000,1.000000,0.000000,31.000000,260.000000,1.000000
max,1307.000000,3.00000,80.000000,8.000000,9.000000,512.329200,328.000000,1.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 850 entries, 0 to 849
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   passenger_id  850 non-null    int64
 1   pclass        850 non-null    int64
 2   sex           850 non-null    object
 3   age           850 non-null    float64
 4   sibsp         850 non-null    int64
 5   parch         850 non-null    int64
 6   ticket        850 non-null    object
 7   fare          849 non-null    float64
 8   cabin         191 non-null    object
 9   embarked      849 non-null    object
 10  boat          308 non-null    object
 11  body          73 non-null     float64
 12  home.dest     464 non-null    object
 13  survived      850 non-null    int64
dtypes: float64(3), int64(5), object(6)
memory usage: 93.1+ KB

In [ ]:
df['age'] = (df['age'] - df['age'].min())/(df['age'].max()-df['age'].min())

In [ ]:
sum(df['age']>=1)

1

In [ ]:
df[df['age']==df['age'].max()]['cabin']

177    A23
Name: cabin, dtype: object

In [ ]:
df['age'] = (df['age'] - df['age'].mean())/(df['age'].std())

In [ ]:
df['age'].std()
df['age'].mean()

np.float64(-1.9226450497038004e-16)

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
le = LabelEncoder()
oe = OrdinalEncoder()
df['sex'] = le.fit_transform(df['sex'])
df['sex'] = oe.fit_transform(df[['sex']])

In [ ]:
df['sex']

0      0.0
1      1.0
2      0.0
3      0.0
4      1.0
      ...
845    1.0
846    1.0
847    0.0
848    0.0
849    1.0
Name: sex, Length: 850, dtype: float64

In [ ]:
df['sex']

0      0.0
1      1.0
2      0.0
3      0.0
4      1.0
      ...
845    1.0
846    1.0
847    0.0
848    0.0
849    1.0
Name: sex, Length: 850, dtype: float64

In [ ]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()
ohe.fit_transform(df[['sex']]).toarray()
ohe.get_feature_names_out()
ohe_df = pd.DataFrame(
    ohe.fit_transform(df[['sex']]).toarray(),
     columns=ohe.get_feature_names_out()
 )
df = pd.concat([df,ohe_df],axis=1)
df

,passenger_id,pclass,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,survived,sex_0.0,sex_1.0
0,1216,3,0.0,0.000000,0,0,335432,7.7333,NaN,Q,13,NaN,NaN,1,1.0,0.0
1,699,3,1.0,0.653096,0,0,315089,8.6625,NaN,S,NaN,NaN,Croatia,0,0.0,1.0
2,1267,3,0.0,0.036979,1,1,345773,24.1500,NaN,S,NaN,NaN,NaN,0,1.0,0.0
3,449,2,0.0,1.885332,1,3,29105,23.0000,NaN,S,4,NaN,"Cornwall / Akron, OH",1,1.0,0.0
4,576,2,1.0,0.807126,0,0,28221,13.0000,NaN,S,NaN,NaN,"Barre, Co Washington, VT",0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
845,158,1,1.0,1.962347,0,0,680,50.0000,C39,S,NaN,NaN,London / Birmingham,0,0.0,1.0
846,174,1,1.0,2.193391,0,0,11771,29.7000,B37,C,NaN,258.0,"Buffalo, NY",0,0.0,1.0
847,467,2,0.0,-0.425109,1,0,244367,26.0000,NaN,S,12,NaN,"Moscow / Bronx, NY",1,1.0,0.0
848,1112,3,0.0,-2.042418,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S,NaN,NaN,NaN,0,1.0,0.0
849,425,2,1.0,1.731302,0,0,250647,13.0000,NaN,S,NaN,19.0,"Bronx, NY",0,0.0,1.0

In [ ]:
df.head()

,passenger_id,pclass,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,survived,sex_0.0,sex_1.0
0,1216,3,0.0,0.000000,0,0,335432,7.7333,NaN,Q,13,NaN,NaN,1,1.0,0.0
1,699,3,1.0,0.653096,0,0,315089,8.6625,NaN,S,NaN,NaN,Croatia,0,0.0,1.0
2,1267,3,0.0,0.036979,1,1,345773,24.1500,NaN,S,NaN,NaN,NaN,0,1.0,0.0
3,449,2,0.0,1.885332,1,3,29105,23.0000,NaN,S,4,NaN,"Cornwall / Akron, OH",1,1.0,0.0
4,576,2,1.0,0.807126,0,0,28221,13.0000,NaN,S,NaN,NaN,"Barre, Co Washington, VT",0,0.0,1.0

In [ ]:
df = df[['pclass','sex']]

In [ ]:
df

     pclass  sex
0         3  0.0
1         3  1.0
2         3  0.0
3         2  0.0
4         2  1.0
..      ...  ...
845       1  1.0
846       1  1.0
847       2  0.0
848       3  0.0
849       2  1.0

[850 rows x 2 columns]

In [ ]:
df = pd.get_dummies(df,dtype=int)

In [ ]:
df

     pclass  sex
0         3  0.0
1         3  1.0
2         3  0.0
3         2  0.0
4         2  1.0
..      ...  ...
845       1  1.0
846       1  1.0
847       2  0.0
848       3  0.0
849       2  1.0

[850 rows x 2 columns]

**Min-Max Feature Scaling**

In [1]:
import pandas as pd

# Create data
df = pd.DataFrame([
    [180000, 110, 18.9, 1400],
    [360000, 905, 23.4, 1800],
    [230000, 230, 14.0, 1300],
    [60000, 450, 13.5, 1500]
], columns=['Col A', 'Col B', 'Col C', 'Col D'])

df_min_max_scaled = df.copy()

# Apply normalization technique
for column in df_min_max_scaled.columns:
    df_min_max_scaled[column] = (
        df_min_max_scaled[column] - df_min_max_scaled[column].min()
    ) / (
        df_min_max_scaled[column].max() - df_min_max_scaled[column].min()
    )

# View normalized data
print(df_min_max_scaled)

      Col A     Col B     Col C  Col D
0  0.400000  0.000000  0.545455    0.2
1  1.000000  1.000000  1.000000    1.0
2  0.566667  0.150943  0.050505    0.0
3  0.000000  0.427673  0.000000    0.4

# **Z-Score Method**

In [2]:

# Create a copy of the data
df_z_score = df.copy()

# Apply Z-Score normalization
for column in df_z_score.columns:
    df_z_score[column] = (
        df_z_score[column] - df_z_score[column].mean()
    ) / df_z_score[column].std()

# View normalized data
print(df_z_score)

      Col A     Col B     Col C    Col D
0 -0.221422 -0.895492  0.311486 -0.46291
1  1.227884  1.373564  1.278167  1.38873
2  0.181163 -0.552993 -0.741122 -0.92582
3 -1.187625  0.074922 -0.848531  0.00000